---
- name: Set timezone to Europe/Istanbul
  community.general.timezone:
    name: Europe/Istanbul
    
- name: Set SELinux to permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: 
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: SELinux disable
  ansible.posix.selinux:
    state: disabled
  notify:
    - stop firewalld

