---
- name: Set timezone to Europe/Istanbul
  community.general.timezone:
    name: Europe/Istanbul
    
- name: Set SELinux running mode to permissive
  ansible.builtin.command: setenforce 0
  when: ansible_selinux.status == "enabled"

- name: SELinux disable
  ansible.posix.selinux:
    state: disabled
  notify:
    - stop firewalld
