---
- name: Storage Edit
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?Storage='
    line: 'Storage=persistent'
    state: present
    backup: true
  notify:
    - restart systemd-journald

- name: Configure systemd default limits
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    state: present
    backup: true
  loop:
    - { key: 'DefaultLimitNOFILE', value: '524288' }
    - { key: 'DefaultLimitNPROC', value: '524288' }
  notify: systemd daemon reload

- name: Deploy chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart chronyd

- name: Configure SMTP relay
  community.general.postconf:
    name: relayhost
    value: "{{ relay_host }}"
  notify:
    - restart postfix

- name: Update /etc/hosts from inventory
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for h in groups['all'] %}
      {{ hostvars[h].ansible_host }} {{ h }}.{{ domain }} {{ h }}
      {% endfor %}
